/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdmin;

import UserInterface.BusinessAdmin.*;
import Business.Business;
import Business.DistributorEnterprise;
import Business.Employee;
import Business.Enterprise;
import Business.EnterpriseDirectory;
import Business.EnterpriseLicenseApprovalRequest;
import Business.CDCEnterprise;
import Business.FederalRegulatoryOffice;
import Business.HospitalEnterprise;
import Business.ManufacturerEnterprise;
import Business.Network;
import Business.Roles.EnterpriseAdminRole;
import Business.StateRegulatoryOffice;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bethi
 */
public class CreateEnterpriseAdmin extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    UserAccount userAccount;
    ManageEnterpriseJPanel me;

    /**
     * Creates new form CreateEnterpriseAdmin
     */
    public CreateEnterpriseAdmin(JPanel userProcessContainer, Business business,UserAccount userAccount,ManageEnterpriseJPanel me) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.userAccount=userAccount;
        this.me=me;
         for(Object o:Enterprise.Type.values()){
             cmbEnterpriseType.addItem(o.toString());
         }
         JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_1blu2.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbEnterpriseType = new javax.swing.JComboBox();
        buttonSubmit = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtUserName1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create Enterprise");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Enterprise Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Enterprise Type");

        buttonSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok.png"))); // NOI18N
        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nav_left_red.png"))); // NOI18N
        buttonBack.setText("back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Mobile");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SSN");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("DOB");

        dateChooserCombo1.setCalendarBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel1)
                .addContainerGap(325, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(cmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSubmit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBack)
                    .addComponent(buttonSubmit))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed

        Employee e;
        UserAccount ua;
        String s1=txtPassword1.getPassword().toString();
        Network net=business.getNetDir().getNetworkByUserAccount(userAccount);
         if(txtEnterpriseName.getText().isEmpty()||txtUserName1.getText().isEmpty()||s1.isEmpty()){
    JOptionPane.showMessageDialog(userProcessContainer, "Please fill the required fields", "Required fields are empty", 0);
    return;
    
}
        if(business.isUserNamePresent(txtUserName1.getText(),business)){
            
            JOptionPane.showMessageDialog(userProcessContainer, "UserName Exists", "UserName Exists", 0);
            return;
        }
         if(cmbEnterpriseType.getSelectedItem().equals(Enterprise.Type.CDC.toString())){
            {
        for(Enterprise entp:net.getEntDirectory().getEnterpriseList()){
            if(entp.getClass().equals(CDCEnterprise.class)){
         JOptionPane.showMessageDialog(userProcessContainer, "An CDC enterprise is already present", "Entity Available", 0);        
         return;
            }
        }}
        }
         long temp;
         try{
        temp=Long.parseLong(txtSSN.getText());
        }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(userProcessContainer, "Please enter a valid number", "Invalid value", 0);
           return;
        }
         long temp1;
         try{
        temp1=Long.parseLong(txtPhoneNumber.getText());
        }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(userProcessContainer, "Please enter a valid number", "Invalid value", 0);
           return;
        }
         Network n=business.getNetDir().getNetworkByUserAccount(userAccount);
         Enterprise ent=null;
         if(((String)cmbEnterpriseType.getSelectedItem()).equals(Enterprise.Type.MANUFACTURER.toString())){
             ent=new ManufacturerEnterprise(txtEnterpriseName.getText()) ;
             
             EnterpriseLicenseApprovalRequest ela=new EnterpriseLicenseApprovalRequest();
             ela.setReqEnterprise(ent);
             
             for(Enterprise enter:n.getEntDirectory().getEnterpriseList()){
                 if(enter.getClass().equals(FederalRegulatoryOffice.class)){
                     FederalRegulatoryOffice fdr=(FederalRegulatoryOffice)enter;
                     fdr.getLicenseApprovalDepartment().getWorkQueue().addWR(ela);
                 }
             }
             
         }else if(((String)cmbEnterpriseType.getSelectedItem()).equals(Enterprise.Type.DISTRIBUTOR.toString())){
              ent=new DistributorEnterprise(txtEnterpriseName.getText()) ;
              EnterpriseLicenseApprovalRequest ela=new EnterpriseLicenseApprovalRequest();
             ela.setReqEnterprise(ent);
             for(Enterprise enter:n.getEntDirectory().getEnterpriseList()){
                 if(enter.getClass().equals(StateRegulatoryOffice.class)){
                     StateRegulatoryOffice fdr=(StateRegulatoryOffice)enter;
                     fdr.getLicenseApprovalDepartment().getWorkQueue().addWR(ela);
                 }}
         }else if(((String)cmbEnterpriseType.getSelectedItem()).equals(Enterprise.Type.HospitalEnterprise.toString())){
              ent=new HospitalEnterprise(txtEnterpriseName.getText()) ;
              EnterpriseLicenseApprovalRequest ela=new EnterpriseLicenseApprovalRequest();
             ela.setReqEnterprise(ent);
             for(Enterprise enter:n.getEntDirectory().getEnterpriseList()){
                 if(enter.getClass().equals(StateRegulatoryOffice.class)){
                     StateRegulatoryOffice fdr=(StateRegulatoryOffice)enter;
                     fdr.getLicenseApprovalDepartment().getWorkQueue().addWR(ela);
                 }}
         }else{
         
            ent=net.getEntDirectory().newEnterprise(txtEnterpriseName.getText(), (String)cmbEnterpriseType.getSelectedItem());
         }
            e = ent.getEmpd().newEmployee();
          
            ua= ent.getUad().newUserAccount();
            ent.setEnterpriseType((String)cmbEnterpriseType.getSelectedItem());
        
        e.setFirstName(txtEnterpriseName.getText());
        e.setLastName(txtEnterpriseName.getText());
         e.setDob(dateChooserCombo1.getSelectedDate());
        
        e.setMobile(temp1);
        e.setSSN(temp);
        
        
        
        ua.setUserName(txtUserName1.getText());
        ua.setPassword(String.valueOf(txtPassword1.getPassword()));
        
        ua.setPerson(e);
        ua.setRole(new EnterpriseAdminRole());
        me.refreshEmployeeTable();
        userProcessContainer.remove(this);

        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        

    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        me.refreshEmployeeTable();
        userProcessContainer.remove(this);

        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox cmbEnterpriseType;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUserName1;
    // End of variables declaration//GEN-END:variables
}
