/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.InventoryManager;

import Business.Business;
import Business.Carton;
import Business.Enterprise;
import Business.InventoryManagementOrg;
import Business.Network;
import Business.Organization;
import Business.RequestForVaccines;
import Business.ReturnSafeVaccinesRequest;
import Business.ShippingRequest;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bethi
 */
public class InventoryWorkQueueJPanel extends javax.swing.JPanel {

    Business b;
    private JPanel userProcessContainer;
    private UserAccount userAccount;

    /**
     * Creates new form SentRequestJPanel
     */
    public InventoryWorkQueueJPanel(JPanel upc, Business b, UserAccount ua) {
        initComponents();

        this.b = b;
        userProcessContainer = upc;
        userAccount = ua;

        refreshWorkReqTable();
     JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/vaccine.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    public void refreshWorkReqTable() {
        int rowCount = workReqTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) workReqTable.getModel()).removeRow(i);

        }
        Network net=b.getNetDir().getNetworkByUserAccount(userAccount);
        
        Enterprise enterprise=net.getEntDirectory().getEnterpriseByUserAccount(userAccount);
        Organization o = enterprise.getOrganizationByUserAccount(userAccount);
        for (WorkRequest wr : o.getWorkQueue().getWrList()) {
            if(wr.getClass().equals(ShippingRequest.class)){
            ShippingRequest mwr = (ShippingRequest) wr;
            Object row[] = new Object[6];
            row[0] = mwr;
            row[1] = WorkRequest.WRType.ShippingRequest;
            row[2]=mwr.getSender();
            row[3] = mwr.getReceiver();
            row[4] = mwr.getDestination();
            row[5] = mwr.getStatus();


            ((DefaultTableModel) workReqTable.getModel()).addRow(row);
            }else if(wr.getClass().equals(RequestForVaccines.class)){
                RequestForVaccines mwr = (RequestForVaccines) wr;
            Object row[] = new Object[6];
            row[0] = mwr;
            row[1] = WorkRequest.WRType.RequestForVaccines;
            row[2]=mwr.getSender();
            row[3] = mwr.getReceiver();
            row[4] = mwr.getDestination();
            row[5] = mwr.getStatus();


            ((DefaultTableModel) workReqTable.getModel()).addRow(row);
            }else if(wr.getClass().equals(ReturnSafeVaccinesRequest.class)){
                ReturnSafeVaccinesRequest mwr = (ReturnSafeVaccinesRequest) wr;
            Object row[] = new Object[6];
            row[0] = mwr;
            row[1] = WorkRequest.WRType.ReturnSafeVaccinesRequest;
            row[2]= "FDA";
            row[3] = mwr.getReceiver();
            row[4] = mwr.getDestination();
            row[5] = mwr.getStatus();


            ((DefaultTableModel) workReqTable.getModel()).addRow(row);
            }

        }
        if (workReqTable.getRowCount() > 0) {
            workReqTable.changeSelection(0, 0, false, false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workReqTable = new javax.swing.JTable();
        buttonBack = new javax.swing.JButton();
        buttonAssign = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory Work Queue");

        workReqTable.setAutoCreateRowSorter(true);
        workReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request Date", "Type", "Sender", "Receiver", "Destination", "Status"
            }
        ));
        jScrollPane1.setViewportView(workReqTable);

        buttonBack.setText("back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonAssign.setText("Process ");
        buttonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(buttonBack)))
                        .addGap(0, 264, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAssign)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAssign)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAssignActionPerformed
        int selectetedRow = workReqTable.getSelectedRow();
if(selectetedRow<0){
    JOptionPane.showMessageDialog(userProcessContainer,"Select a request", "Select request", 0);
    return;
}

WorkRequest wr=(WorkRequest)workReqTable.getValueAt(selectetedRow, 0);
if(wr.getReceiver()==null||wr.getReceiver()==userAccount){
    if(wr.getStatus()!=WorkRequest.StatusType.Resolved.toString()){
if(wr.getClass().equals(ShippingRequest.class)){
    ShippingRequest sr = (ShippingRequest)wr;
        sr.setReceiver(userAccount);
            sr.setStatus("Received");
            
        JPanel panel = new PackageVerificationJPanel(userProcessContainer, b, userAccount,sr,this);
        userProcessContainer.add("ViewRequestDetails", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);

        
}else if(wr.getClass().equals(RequestForVaccines.class)){
    RequestForVaccines rfd=(RequestForVaccines)wr;
JPanel panel = new ViewRequestDetails(userProcessContainer, b, userAccount,rfd,this);
        userProcessContainer.add("ViewRequestDetails", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    
}else if(wr.getClass().equals(ReturnSafeVaccinesRequest.class)){
    ReturnSafeVaccinesRequest rfd=(ReturnSafeVaccinesRequest)wr;
InventoryManagementOrg io=(InventoryManagementOrg)b.getNetDir().getNetworkByUserAccount(userAccount).getEnterpriseByUserAccount(userAccount).getOrganizationByUserAccount(userAccount);
    for(Carton c:rfd.getCartonList()){
        io.getInvCatalog().addCarton(c);
    }
    rfd.setStatus(WorkRequest.StatusType.Resolved.toString());
    
}
      //
        
        //
        
        refreshWorkReqTable();
    }else{
            JOptionPane.showMessageDialog(userProcessContainer,"Already Resolved", "Already Resolved", 1);
        }   
    }else{
            JOptionPane.showMessageDialog(userProcessContainer,"Already Resolved", "Already Resolved", 1);
        }
    }//GEN-LAST:event_buttonAssignActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAssign;
    private javax.swing.JButton buttonBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workReqTable;
    // End of variables declaration//GEN-END:variables
}
