/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 
 
 */
package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.VaccineDispositionOrganization;
import Business.VaccineManfacturingOrg;
import Business.VaccineTestingOrganization;
import Business.Employee;
import Business.Enterprise;
import Business.InvestigationDepartment;
import Business.LicenseApprovalDepartment;
import Business.Network;
import Business.Organization;
import Business.Roles.VaccineDispositionerRole;
import Business.Roles.VaccineManufacturerRole;
import Business.Roles.VaccineTesterRole;
import Business.Roles.InventoryManagerRole;
import Business.Roles.InvestigationOfficialRole;
import Business.Roles.LicenseOfficialRole;
import Business.Roles.SalesEmployeeRole;
import Business.Roles.ShipmentManagerRole;
import Business.ProviderOrganization;
import Business.ShippingOrganization;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Bethi
 */
public class AddUserAccountJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    Business business;
    ManageUserAccounts mua;

    /** Creates new form BusinessAdminWorkAreaJPanel */
    public AddUserAccountJPanel(JPanel upc, Business business, UserAccount ua,ManageUserAccounts mua) {
        initComponents();

        this.business = business;
        userProcessContainer = upc;
        userAccount = ua;
        this.mua=mua;
        
        organizationJComboBox.removeAllItems();
        
        organizationJComboBox.addItem((Organization)enterprise);  
        Network net=business.getNetDir().getNetworkByUserAccount(ua);
        enterprise=net.getEnterpriseByUserAccount(ua);
        for(Organization org : enterprise.getOrgDirectory().getOrgList()) {
            organizationJComboBox.addItem(org);
        }
        
        
     JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_1blu2.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        usernameJTextField = new javax.swing.JTextField();
        passwordJTextField = new javax.swing.JTextField();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        addEmployeeeJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        employeeJComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Password:");

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Username:");

        addEmployeeeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok.png"))); // NOI18N
        addEmployeeeJButton.setText("Submit");
        addEmployeeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeeJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Organization:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Add UserAccount");

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nav_left_red.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Employee:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(layout.createSequentialGroup()
                                .add(backJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(addEmployeeeJButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(53, 53, 53)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel4)
                                            .add(jLabel5))
                                        .add(31, 31, 31)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(usernameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(passwordJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(layout.createSequentialGroup()
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel3)
                                            .add(jLabel7))
                                        .add(18, 18, 18)
                                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                            .add(employeeJComboBox, 0, 170, Short.MAX_VALUE)
                                            .add(organizationJComboBox, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .add(layout.createSequentialGroup()
                        .add(171, 171, 171)
                        .add(jLabel2)))
                .addContainerGap(421, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabel2)
                .add(50, 50, 50)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(organizationJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(employeeJComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(usernameJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passwordJTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .add(88, 88, 88)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backJButton)
                    .add(addEmployeeeJButton))
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        mua.refreshUserAccountTable();
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }
        // TODO add your handling code here:         userProcessContainer.remove(this);         CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();         cardLayout.previous(userProcessContainer);     }//GEN-LAST:event_backJButtonActionPerformed

        private void addEmployeeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeeJButtonActionPerformed

           
            if(usernameJTextField.getText().isEmpty()||passwordJTextField.getText().isEmpty()){
    JOptionPane.showMessageDialog(userProcessContainer, "Please fill the required fields", "Required fields are empty", 0);
    return;
}
            Organization organization = (Organization)organizationJComboBox.getSelectedItem();
            Employee employee = (Employee)employeeJComboBox.getSelectedItem();
            
            UserAccount ua = organization.getUad().newUserAccount();
            ua.setUserName(usernameJTextField.getText());
            ua.setPassword(passwordJTextField.getText());
            ua.setPerson(employee);
            
            if(organization.getClass().equals(ProviderOrganization.class)){
                ua.setRole(new SalesEmployeeRole());
            }else if(organization.getClass().equals(ShippingOrganization.class)){
                ua.setRole(new ShipmentManagerRole());
            }else if(organization.getClass().equals(VaccineManfacturingOrg.class)){
                ua.setRole(new VaccineManufacturerRole());
            }else if(organization.getClass().equals(LicenseApprovalDepartment.class)){
                ua.setRole(new LicenseOfficialRole());
            }else if(organization.getClass().equals(VaccineTestingOrganization.class)){
                ua.setRole(new VaccineTesterRole());
            }else if(organization.getClass().equals(InvestigationDepartment.class)){
                ua.setRole(new InvestigationOfficialRole());
            }else if(organization.getClass().equals(VaccineDispositionOrganization.class)){
                ua.setRole(new VaccineDispositionerRole());
            }
            else{
                ua.setRole(new InventoryManagerRole());
            }
            
            mua.refreshUserAccountTable();
        userProcessContainer.remove(this);

        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        
        // TODO add your handling code here:         JPanel panel = new AddEnterpriseJPanel(userProcessContainer, business, userAccount);         userProcessContainer.add("AddEnterpriseJPanel", panel);         CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();         cardLayout.next(userProcessContainer);     }//GEN-LAST:event_addEmployeeeJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
        
        Organization organization = (Organization)organizationJComboBox.getSelectedItem();
        
        if(organization != null) {
            employeeJComboBox.removeAllItems();
            for(Employee employee : organization.getEmpd().getEmpList()) {
                employeeJComboBox.addItem(employee);
            }
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeeJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField passwordJTextField;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
