/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Business;
import Business.Carton;
import Business.VaccinePackage;
import Business.Enterprise;
import Business.CDCEnterprise;
import Business.InventoryManagementOrg;
import Business.Network;
import Business.Patient;
import Business.ReportCDCRequest;
import Business.UserAccount;
import Business.WorkRequest;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bethi
 */
public class InventoryCatalogJPanel extends javax.swing.JPanel {

    Business b;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ArrayList<VaccinePackage> reportList;
    private ArrayList<VaccinePackage> tempList;

    /**
     * Creates new form InventorySentRequestJPanel
     */
    public InventoryCatalogJPanel(JPanel upc, Business b, UserAccount ua) {
        initComponents();

        this.b = b;
        userProcessContainer = upc;
        userAccount = ua;
        reportList = new ArrayList<VaccinePackage>();
        refreshWorkReqTable();
     JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_drug_good.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    private void refreshWorkReqTable() {
        int rowCount = workReqTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) workReqTable.getModel()).removeRow(i);

        }
        Patient p = (Patient) userAccount.getPerson();




        for (VaccinePackage dPack : p.getPackageList()) {

            Object row[] = new Object[5];
            row[0] = dPack;
            row[1] = dPack.getPackageId();
            row[2] = dPack.getCartonId();
            row[3] = dPack.getDateOfExpiry().getTime().toString();
            row[4] = dPack.getStatus();


            ((DefaultTableModel) workReqTable.getModel()).addRow(row);
        }

        if (workReqTable.getRowCount() > 0) {
            workReqTable.changeSelection(0, 0, false, false);
        }
    }
private void refreshreportingTable() {
        int rowCount = reportingTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) reportingTable.getModel()).removeRow(i);

        }
        Patient p = (Patient) userAccount.getPerson();




        for (VaccinePackage dPack : reportList) {

            Object row[] = new Object[5];
            row[0] = dPack;
            row[1] = dPack.getPackageId();
            row[2] = dPack.getCartonId();
            row[3] = dPack.getDateOfExpiry().getTime().toString();
            row[4] = dPack.getStatus();


            ((DefaultTableModel) reportingTable.getModel()).addRow(row);
        }

        if (reportingTable.getRowCount() > 0) {
            reportingTable.changeSelection(0, 0, true, true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workReqTable = new javax.swing.JTable();
        buttonBack = new javax.swing.JButton();
        buttonReportToFDA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportingTable = new javax.swing.JTable();
        buttonReportToFDA1 = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        txtReason = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory Catalog");

        workReqTable.setAutoCreateRowSorter(true);
        workReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine", "Package ID", "Carton ID", "Expiry Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workReqTable);

        buttonBack.setText("back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonReportToFDA.setText("Add to Report");
        buttonReportToFDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportToFDAActionPerformed(evt);
            }
        });

        reportingTable.setAutoCreateRowSorter(true);
        reportingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaccine", "Package ID", "Carton ID", "Expiry Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reportingTable);

        buttonReportToFDA1.setText("Send Report");
        buttonReportToFDA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportToFDA1ActionPerformed(evt);
            }
        });

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reason");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeButton)
                            .addComponent(buttonBack))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonReportToFDA)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonReportToFDA1)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(buttonReportToFDA)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReportToFDA1)
                    .addComponent(removeButton)
                    .addComponent(txtReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(buttonBack)
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonReportToFDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportToFDAActionPerformed
        int selectetedRow = workReqTable.getSelectedRow();
        if (selectetedRow < 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Select a request", "Select request", 0);
            return;
        }

        VaccinePackage dp = (VaccinePackage) workReqTable.getValueAt(selectetedRow, 0);

        reportList.add(dp);
        Patient p=(Patient)userAccount.getPerson();
        p.getPackageList().remove(dp);
        
        refreshreportingTable();


        refreshWorkReqTable();
    }//GEN-LAST:event_buttonReportToFDAActionPerformed

    private void buttonReportToFDA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportToFDA1ActionPerformed

        
      for(Network n:b.getNetDir().getNetworkList()){
            for(Enterprise ent:n.getEntDirectory().getEnterpriseList()){
                if(ent.getClass().equals(CDCEnterprise.class)){
                    CDCEnterprise fent=(CDCEnterprise)ent;
                    ReportCDCRequest rfr=new ReportCDCRequest();
                    fent.getInvestigationOrg().getWorkQueue().addWR(rfr);
                   
                   Patient p=(Patient)userAccount.getPerson();
                    p.getSentRequests().addWR(rfr);
 
                    tempList=new ArrayList<VaccinePackage>();
                    
                    for(VaccinePackage dp:reportList){
                    rfr.addPackage(dp);
                    tempList.add(dp);
                    }
                    for(VaccinePackage dp:tempList){
                    reportList.remove(dp);
                    }                    

                    rfr.setSender(userAccount);
                    rfr.setDestination(fent);
                    rfr.setPatient(p);
                    rfr.setStatus(WorkRequest.StatusType.SentToFDA.toString());
                    rfr.setReasonForReporting(txtReason.getText());
                }

            }
        }
      userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonReportToFDA1ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
         int selectetedRow = reportingTable.getSelectedRow();
        if (selectetedRow < 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Select a request", "Select request", 0);
            return;
        }

        VaccinePackage dp = (VaccinePackage) reportingTable.getValueAt(selectetedRow, 0);

        reportList.remove(dp);
        Patient p=(Patient)userAccount.getPerson();
        p.getPackageList().add(dp);
        
        refreshreportingTable();


        refreshWorkReqTable();

    }//GEN-LAST:event_removeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonReportToFDA;
    private javax.swing.JButton buttonReportToFDA1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable reportingTable;
    private javax.swing.JTextField txtReason;
    private javax.swing.JTable workReqTable;
    // End of variables declaration//GEN-END:variables
}
