/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Alert;
import Business.Business;
import Business.Carton;
import Business.VaccinePackage;
import Business.Enterprise;
import Business.InventoryManagementOrg;
import Business.Patient;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bethi
 */
public class PatientWorkareaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Business business;
    UserAccount ua;

    /**
     * Creates new form InventoryManagerJPanel
     */
    public PatientWorkareaJPanel(JPanel userProcessContainer, Business business, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.ua = ua;



        refreshWorkReqTable();

     JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_drug_good.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    private void refreshWorkReqTable() {
        int rowCount = workReqTable.getRowCount();

        for (int i = rowCount - 1; i >= 0; i--) {
            ((DefaultTableModel) workReqTable.getModel()).removeRow(i);

        }


        Patient pat = (Patient) ua.getPerson();

        for (Alert a : pat.getAlertList()) {


            Object row[] = new Object[3];
            row[0] = a;
            if(a.getIncidentOrigin()!=null){
            row[1] = a.getIncidentOrigin();
            }
            boolean flag = false;
            for (VaccinePackage dpa : a.getPackageList()) {

                for (VaccinePackage dpi : pat.getPackageList()) {
                    if (dpa == dpi) {
                        flag = true;

                    }
                }

            }
            if (flag) {
                row[2] = "Active Alert";
            } else {
                row[2] = "Passive Alert";
            }


            ((DefaultTableModel) workReqTable.getModel()).addRow(row);


        }
        if (workReqTable.getRowCount() > 0) {
            workReqTable.changeSelection(0, 0, false, false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSentRequests = new javax.swing.JButton();
        buttonRequestTest = new javax.swing.JButton();
        buttonInventory = new javax.swing.JButton();
        buttonViewDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workReqTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        buttonViewSuspectedDrugs1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonSentRequests.setText("Sent Requests");
        buttonSentRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSentRequestsActionPerformed(evt);
            }
        });

        buttonRequestTest.setText("Request Vaccine");
        buttonRequestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRequestTestActionPerformed(evt);
            }
        });

        buttonInventory.setText("View Inventory");
        buttonInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInventoryActionPerformed(evt);
            }
        });

        buttonViewDetails.setText("View Personal Details");
        buttonViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewDetailsActionPerformed(evt);
            }
        });

        workReqTable.setAutoCreateRowSorter(true);
        workReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaccine", "Incident Origin", "Status"
            }
        ));
        jScrollPane1.setViewportView(workReqTable);

        jButton2.setText("View Alert Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonViewSuspectedDrugs1.setText("View All Alerts");
        buttonViewSuspectedDrugs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewSuspectedDrugs1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonViewDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonSentRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRequestTest, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(buttonViewSuspectedDrugs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonViewDetails)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRequestTest)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSentRequests)
                        .addGap(18, 18, 18)
                        .addComponent(buttonInventory)
                        .addGap(18, 18, 18)
                        .addComponent(buttonViewSuspectedDrugs1)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSentRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSentRequestsActionPerformed
        JPanel panel = new PatientSentRequestJPanel(userProcessContainer, business, ua);
        userProcessContainer.add("InventorySentRequestJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_buttonSentRequestsActionPerformed

    private void buttonRequestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRequestTestActionPerformed
        // TODO add your handling code here:
        JPanel panel = new RequestForVaccinesJPanel(userProcessContainer, business, ua);
        userProcessContainer.add("SalesRequestJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_buttonRequestTestActionPerformed

    private void buttonInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInventoryActionPerformed
        JPanel panel = new InventoryCatalogJPanel(userProcessContainer, business, ua);
        userProcessContainer.add("InventoryCatalogJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_buttonInventoryActionPerformed

    private void buttonViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewDetailsActionPerformed
        JPanel panel = new ViewDetailsJPanel(userProcessContainer, business, ua);
        userProcessContainer.add("View Details", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_buttonViewDetailsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectetedRow = workReqTable.getSelectedRow();
        if (selectetedRow < 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Select an alert", "Select alert", 0);
            return;
        }

        Alert a = (Alert) workReqTable.getValueAt(selectetedRow, 0);
        JPanel panel = new AlertJPanel(userProcessContainer, business, ua, a);
        userProcessContainer.add("AlertJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonViewSuspectedDrugs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewSuspectedDrugs1ActionPerformed
        JPanel panel = new AllAlertsJPanel(userProcessContainer, business, ua);
        userProcessContainer.add("AllAlertsJPanel", panel);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_buttonViewSuspectedDrugs1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonInventory;
    private javax.swing.JButton buttonRequestTest;
    private javax.swing.JButton buttonSentRequests;
    private javax.swing.JButton buttonViewDetails;
    private javax.swing.JButton buttonViewSuspectedDrugs1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workReqTable;
    // End of variables declaration//GEN-END:variables
}
