/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package UserInterface.LicenseOfficial;


import Business.Business;
import Business.Vaccine;
import Business.VaccineLicenseRequest;
import Business.Enterprise;
import Business.CDCEnterprise;
import Business.ManufacturerEnterprise;
import Business.Network;
import Business.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Bethi
 */
public class VaccineLicenseRequestJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private UserAccount userAccount;
Business b;
VaccineLicenseRequest sr;
LicenseOfficialWorkQueueJPanel swq;

    /** Creates new form BusinessAdminWorkAreaJPanel */
    public VaccineLicenseRequestJPanel(JPanel upc, Business b, UserAccount ua,VaccineLicenseRequest sr,LicenseOfficialWorkQueueJPanel swq) {
        initComponents();

        this.b=b;
        userProcessContainer = upc;
        userAccount = ua;
        this.sr=sr;
        this.swq=swq;
        
        lblVaccineName.setText(sr.getVaccineName());
        lblVaccineCompound.setText(sr.getVaccineCompound());
        lblVaccineWeight.setText(Integer.toString(sr.getVaccineWeight()));
        Network reqNet=b.getNetDir().getNetworkByUserAccount(sr.getSender());
        Enterprise reqEnt=reqNet.getEnterpriseByUserAccount(sr.getSender());
        lblRequestingEnterprise.setText(reqEnt.toString());
               
     JPanel panel = this;
        panel.setOpaque(false);
        panel.setPreferredSize(this.getPreferredSize());

    }
    ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/Resources/rsz_drug_good.jpg"));

    @Override
    protected void paintComponent(Graphics g) {
        g.drawImage(icon.getImage(), 0, 0, null);
        super.paintComponent(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        buttonApproveDrugRequest = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonRejectDrugRequest1 = new javax.swing.JButton();
        lblRequestingEnterprise = new javax.swing.JLabel();
        lblVaccineWeight = new javax.swing.JLabel();
        lblVaccineCompound = new javax.swing.JLabel();
        lblVaccineName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Shipping Request");

        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/nav_left_red.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        buttonApproveDrugRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok.png"))); // NOI18N
        buttonApproveDrugRequest.setText("Approve");
        buttonApproveDrugRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonApproveDrugRequestActionPerformed(evt);
            }
        });

        jLabel4.setText("Vaccine Compound");

        jLabel5.setText("Vaccine Weight");

        jLabel6.setText("Vaccine Name");

        jLabel7.setText("Requesting Enterprise");

        buttonRejectDrugRequest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/error.png"))); // NOI18N
        buttonRejectDrugRequest1.setText("Reject");
        buttonRejectDrugRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRejectDrugRequest1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(272, 272, 272)
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .add(64, 64, 64)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(backJButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 313, Short.MAX_VALUE)
                                .add(buttonRejectDrugRequest1)
                                .add(18, 18, 18)
                                .add(buttonApproveDrugRequest))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel5)
                                    .add(jLabel4)
                                    .add(jLabel6))
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(lblVaccineName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblVaccineCompound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblVaccineWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblRequestingEnterprise, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(0, 0, Short.MAX_VALUE)))))
                .add(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(lblVaccineName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel4)
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel5)
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, lblRequestingEnterprise, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel7))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 244, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(backJButton)
                                    .add(buttonApproveDrugRequest)
                                    .add(buttonRejectDrugRequest1))
                                .add(29, 29, 29))
                            .add(layout.createSequentialGroup()
                                .add(lblVaccineWeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(lblVaccineCompound, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        swq.refreshWorkReqTable();
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void buttonApproveDrugRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApproveDrugRequestActionPerformed

       
        Network net=b.getNetDir().getNetworkByUserAccount(userAccount);  
        ManufacturerEnterprise me=(ManufacturerEnterprise)net.getEnterpriseByUserAccount(sr.getSender());
        Vaccine drug=me.getDmo().getVaccinecatalog().newVaccine();
        drug.setName(sr.getVaccineName());
        drug.setCompound(sr.getVaccineCompound());
        drug.setWeight(sr.getVaccineWeight());
        drug.setType(sr.getType());
        sr.setStatus("Approved");
        
        swq.refreshWorkReqTable();
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonApproveDrugRequestActionPerformed

    private void buttonRejectDrugRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRejectDrugRequest1ActionPerformed
        
        sr.setStatus("Rejected");
        
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        swq.refreshWorkReqTable();
    }//GEN-LAST:event_buttonRejectDrugRequest1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton buttonApproveDrugRequest;
    private javax.swing.JButton buttonRejectDrugRequest1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblRequestingEnterprise;
    private javax.swing.JLabel lblVaccineCompound;
    private javax.swing.JLabel lblVaccineName;
    private javax.swing.JLabel lblVaccineWeight;
    // End of variables declaration//GEN-END:variables
}
